### ISSUE TITLE
Confusion about the platform trajectory

### ISSUE THREAD

**Issue by xjy11** [3dgeo-heidelberg/helios#226] opened 2022-05-04 14:46 UTC
What I want to do is restore the scan angle of the real data since it may influence the shape of the waveform. The trajectory of the ALS platform provided by the .trj file includes GPSTime, x, y, z, roll, pitch, and yaw. Is that possible to reproduce the trajectory in the simulation with a defined .trj file? I see there is a demo named als_interpolated_trajectory but the simulated point clouds are different from the linearpath platform. I am not clear about the interpolation here.

Thank you all very much.

**Comment by han16nah** [comment] 2022-05-05 06:58
Dear @xjy11 
Our new "interpolated trajectory" feature should allow exactly this: reproducing a survey based on a real trajectory file, no matter if it's a more or less straight path or a curve. So in general, it should allow reproducing your real survey more closely, given that you also define the other sensor settings (scan angle, pulse frequency, etc.).

However, the feature is still experimental and under development. You can follow the progress in #174.
We just tested the interpolated trajectory with a real trajectory of one of our datasets and noticed some problems, see #227.
We try to take care of this as soon as possible and will then provide a working example for you. 

It is always a great help for our development to have test data. If you want to provide your trajectory and sceneparts, the survey and scene XMLs, and potentially also the expected point cloud output (your real point clouds), we would greatly appreciate this. This is the quickest way to find a solution for your specific problem. 

Best regards
Hannah

**Comment by lwiniwar** [comment] 2022-05-11 19:37
Dear @xjy11,
thank you for providing this example.
As you see in the output, HELIOS++ tries to replicate the *position* and *attitute* of the input trajectory as close as possible. When thinking of an airplane, it might make sense to calculate the yaw from two subsequent points, but this is not a strict limit. For example, winds may shift the airplane perpendicular to its heading direction, while the yaw angle (and therefore the orientation of the laser scanner's scanning plane) stays the same. When you think of ULS systems or helicopters, this becomes even more important, as they may sway to the side (accelerating sidewards by tilting).
Having said that, I see that the output trajectory above perfectly replicates the input trajectory.
Now, for the meaning of the angles:
The 'yaw' angle starts at 0 degrees "north" (i.e., parallel to the secondary axis/y-axis) and increases mathematically positive (counterclockwise), so 90 degrees is due west. This is inverse to the common "yaw" angle as provided as (magnetic) heading.
The 'pitch' angle is positive if the platform' nose (facing in yaw direction) goes up, and negative if it goes down.
The 'roll' angle is positive if the platform's right wing (or arm, again with respect to the yaw) goes up, and negative if it goes down.
You can also see this in the plots in the wiki: https://github.com/3dgeo-heidelberg/helios/wiki/Platforms#dynamic-platforms (scroll down to "multicopter").
I find visualizing the trajectory file by coloring the angles helps a lot. If you find behaviour that is *not* fitting this description, please let us know as it might be a bug and this feature is still very much in development.

Best,
Lukas

**Comment by han16nah** [comment] 2022-05-12 09:41
Dear @xjy11 
please see my update posted on #227 
As @lwiniwar stated, the trajectory output and behaviour is perfectly fine. The issue is that you are probably doing and airborne simulation and expecting the scanner to point downwards and scan left to right. This is applied when using e.g. the platform `data\platforms.xml#sr22` due to the rotations defined in the `scannerMount`. We are currently lacking this option in the `interpolated` trajectory implementation.
We will keep you posted once we have an update about this!

Best,
Hannah

**Comment by han16nah** [comment] 2022-12-14 10:45
There is now the `pasePlatform` argument, which allows using the `scannerMount` defined for the respective platform in the `platform.xml`. We will therefore close this issue.

**Closed by han16nah** 2022-12-14 10:45 UTC
