### ISSUE TITLE
Scene part partially loaded ?

### ISSUE THREAD

**Issue by NanBlanc** [3dgeo-heidelberg/helios#254] opened 2022-08-02 20:52 UTC
**The problem**
Some object parts seems to be ignored in the collision with the laser beams, resulting in incomplete objects in point clouds.

**How to reproduce**
1. Recompiling lastest code from git
2. Use a simple scene : Tiff as ground (25x25m), one .obj model for tree axis and one .obj for leafs (8.7, 6.2 and 6.5 Mo respectively). 
3. Do ALS scan.

I can join all the files if needed.

**Your environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - HELIOS++/pyhelios version (or Git revision) that exhibits the issue : Version 1.1.0
 - Last HELIOS++/pyhelios version that did not exhibit the issue (if applicable): Version 1.1.0 (no --version arguement, so hard to tell but I downloaded my old version on July 8 2022)
 - Further system details (if relevant): 64 RAM 

**Screenshots (Optional)**
Expected :
![Selection_169](https://user-images.githubusercontent.com/29095576/182470891-cf7be8d0-bf05-4fac-8862-e8b09ebf0dcc.png)

Actual :
![Selection_170](https://user-images.githubusercontent.com/29095576/182470875-5aa56b1d-4da5-4fa1-9c6e-69b3e18532f0.png)

**Ideas for possible solutions (Optional)**
When not using the latest compilation, my example works fine, which means recent modifications may have introduced this error. Funny things that can help to pin point the source : 
When running the simulation with not-the-last-compilation on the same scene, then redoing it with the lastest version, but without --rebuildScene, everything is fine. Which means it has something to do with the scene building

**Comment by albertoesmp** [comment] 2022-08-02 21:37
Thank you for reporting this. It looks very interesting that the bug was not present in July 08. It is a really nice hint. I'm in the middle of a lot of work but I'll try to solve this as soon as possible.

**Comment by albertoesmp** [comment] 2022-08-03 08:10
Hello again, @NanBlanc .

I've been checking the latest updates but could not find any obvious modification on the scene loading procedure after the 8th of July. I would like to use your survey to debug this issue, so I can start by reproducing it exactly to be on the safe side. Would you mind sharing your survey, scene, and scene parts (tiff file included) data with us? If you are not comfortable with publishing them here at GitHub you can send them privately to us through our email [helios@uni-heidelberg.de](mailto:helios@uni-heidelberg.de)

**Comment by bhoefle-3dgeo** [comment] 2022-08-03 10:23
It might also be good to check the parameters of each version (i.e. have some default parameters changed between the used versions). @albertoesmp, we should also consider writing an extra nicely formatted "log" file for all the parameters used for a simulation in a proper format that allows quick comparison, including all parameters (also default and user set ones). 

e.g. --logFileParameters (?)

**Comment by albertoesmp** [comment] 2022-08-03 12:30
> It might also be good to check the parameters of each version (i.e. have some default parameters changed between the used versions). @albertoesmp, we should also consider writing an extra nicely formatted "log" file for all the parameters used for a simulation in a proper format that allows quick comparison, including all parameters (also default and user set ones).
> 
> e.g. --logFileParameters (?)

I think we have a debugging tool that does something quite similar to what you propose. See https://github.com/3dgeo-heidelberg/helios/blob/dev/doc/debug/DEBUG.md for more information, more concretely the "JSON Report" subsection. With this we can generate JSON files storing the internal state (e.g. survey, scanner and platform variables). Then using the python script at scripts/debug/hda_diff_report.py the JSON files are compared and any difference between them is explicitly pointed by the script output. I can do this once I have the survey to debug this issue. I think it is a very useful tool.

**Comment by NanBlanc** [comment] 2022-08-03 19:40
I just found out that your precompiled version for ubuntu 20.04 https://github.com/3dgeo-heidelberg/helios/releases/download/v1.1.0/helios-plusplus-lin.tar.gz of the 15 march shows the same problem

**Comment by albertoesmp** [comment] 2022-08-04 13:15
Hello again @NanBlanc 

I have some updates on this. I tried the survey with the current development version of HELIOS++ and the output looks good to me. Please, see the screenshot below and correct me if I'm wrong.
![leg000](https://user-images.githubusercontent.com/7394022/182854521-ca4296af-f2dd-488b-b51b-a25426b61320.png)

If I'm right with my previous statement, then I think that the issue might be related to this one: https://github.com/3dgeo-heidelberg/helios/issues/230 In fact, you are also using the `onGround` parameter to place your tree automatically at ground level, which was causing the problem with previous versions.

If I'm right, the good news is that the issue is already solved in the latest development version of the software. You have different options to check this. You could try to compile it manually from the development branch. Alternatively, you could check the artifacts that are generated through Github CI workflow (scroll down a little to see them).

Artifacts for Linux: https://github.com/3dgeo-heidelberg/helios/actions/runs/2796520666
Artifacts for Windows: https://github.com/3dgeo-heidelberg/helios/actions/runs/2796520667

Please, let us know your results if you try with the newer version.

**Comment by albertoesmp** [comment] 2022-08-04 16:59
> I didn't paid attention i was -b 1.1.0 when git cloning, so i indeed didn't used the last dev version. Thanks for the help, It was the same problem as #230. Sorry for the useless bug report.

Don't worry! Thank you for using HELIOS++

I'm closing this issue because it is solved.

Please, let us know if we can help you with anything else.

**Closed by albertoesmp** 2022-08-04 16:59 UTC
Labels: bug
